language: python
python: 3.7

before_install:
  - travis/get_virsorter_db.sh $TRAVIS_BUILD_DIR/virsorter-data-cache

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  # Pipeline env
  - conda env create -f requirements/conda_env.yml
  - conda activate viral_pipeline

  script:
    - echo "Hi!"
    #- bash run_tests.sh

cache:
  directories:
    - $TRAVIS_BUILD_DIR/virsorter-data-cache/
    # TODO: If the env changes then the cache has to be manually cleaned
    - $HOME/miniconda
