language: python
python: 3.7

install:
  # VirSorter DB (this is cached)
  # - bash travis/download_databases.sh $TRAVIS_BUILD_DIR/databases
  # CONDA and the env
  - wget "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  # Pipeline env
  - conda env create -f requirements/conda_env.yml
  - conda activate viral_pipeline
  # Env variables
  - chmod +x $TRAVIS_BUILD_DIR/scripts/*
  - export PATH=$TRAVIS_BUILD_DIR/scripts:$PATH

script:
  - cd $TRAVIS_BUILD_DIR/tests
  # TODO:
  # run only tests that do not require DBs or files from the FTP server
  - cwltest --test tests.yml --tool cwltool -j 12 --verbose -n 1,4,5,6,7,8,9,11

cache:
  directories:
    - databases/vpHMM_database
    - databases/virsorter-data
    # TODO: If the env changes then the cache has to be manually cleaned
    # - $HOME/miniconda
